### ISSUE TITLE
toggleable zoom lock feature

### ISSUE THREAD

**Issue by matt-deboer** [jsbroks/coco-annotator#82]
**Feature Request**
For some scenarios where zooming is overly sensitive (I'm looking at you, Macbook pro oversized touchpad), it would be useful to toggle a lock on the zoom capability.

**Comment by EMCP** [comment]
on large images the zoom is also quite poor.. or unclear.  I find it will really help if we had a tool to move the image and annotations.

**Comment by EMCP** [comment]
performance in general is bad on large large images, but that's probably not trivial to fix either

**Comment by jsbroks** [comment]
@EMCP What version are you on. This should nolonger be an issue #151

**Comment by EMCP** [comment]
according to the site, `v0.8.0`

<img width="259" alt="Screen Shot 2019-04-08 at 8 52 28 PM" src="https://user-images.githubusercontent.com/3691722/55748996-4398b980-5a40-11e9-9f94-3fb07eea7642.png">

**Comment by jsbroks** [comment]
@EMCP Current version is 0.10.2, issue was fixed in 0.9.0. Please consider upgrading. Keep in mind annotation made in 0.8.0 might not be optimization but new annotations will be.

**Comment by EMCP** [comment]
definitely can do!  I had just run off the instructions 1 month ago, but perhaps I need to build from source to get latest release.. in either case, will do!  thanks

**Comment by jsbroks** [comment]
To get the latest:

```
git pull
docker-compose down
docker-compose pull
docker-compose up
```
Normally you wont have to do git pull, but 0.10 was such a large update

**Comment by EMCP** [comment]
I still get crashes, I can hear my CPU whirring hard on these images.. I'm guessing it's testing the limits of VueJS and the algorithm that stores the annotation mask cordinates

**Comment by jsbroks** [comment]
@EMCP Please try to reproduce this on the demo server and provide a link.
